---
title: 'Task 0: Understanding the Problem'
author: "ps7391"
date: "`r format(Sys.Date())`"
output: 
        html_document:
                  keep_md: yes
        md_document:
                  variant: markdown_github
        pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Introduction

The first step in analyzing any new data set is figuring out: (a) what data you have
and (b) what are the standard tools and models used for that type of data. Make sure 
you have downloaded the data from Coursera before heading for the exercises. This 
exercise uses the files named LOCALE.blogs.txt where LOCALE is the each of the four
locales en_US, de_DE, ru_RU and fi_FI. The data is from a corpus called HC Corpora.
See the About the Corpora reading for more details. The files have been language 
filtered but may still contain some foreing text.

In this capstone we will be applying data science in the area of natural language processing. As a first step toward working on this project, you should familiarize yourself with Natural Language Processing, Text Mining, and the associated tools in R. 

### Dataset

This is the training data to get started that will be the basis for most of the capstone. You must download the data from the Coursera site and not from external websites to start.

[Capstone Dataset](https://d396qusza40orc.cloudfront.net/dsscapstone/dataset/Coursera-SwiftKey.zip)

Your original exploration of the data and modeling steps will be performed on this data set. Later in the capstone, if you find additional data sets that may be useful for building your model you may use them.

### Tasks to accomplish

1. Obtaining the data - con you download the data and load/manipulate it in R?
2. Familiarizing yourself with NLP and text mining - Learn about the basics of natural language processing and how it relates to the data science process you have learned in the Data Science Specialization.

### Questions to consider

1. What do the data look like?
2. Where do the data come from?
3. Can you think of any other data sources that might help you in this project?
4. What are the common steps in natural language processing?
5. What are some commone issues in the analysis of text data?
6. What is the relationship between NLP and the concepts you have learned in the Specialization?
